In [ ]:
# s_woo = pd.read_csv('./s_woo.csv',encoding='euc-kr')
# s_woo
# 변수가 좁혀진 데이터

In [1]:
import pandas as pd

- fin_raw_data

In [2]:
fin_raw_data = pd.read_csv('./fin_raw_data.csv',encoding='euc-kr')

In [3]:
fin_raw_data

,날짜,달러원종가,달러원시가,CD91,WTI가,달러위안화,달러엔,달러인덱스,유로달러,유로인덱스,콜금리,코스피종가,BIR,위안화원,엔원
0,2010-01-04,1150.00,1164.07,2.88,81.64,6.83,92.47,92.36,1.44,106.23,1.98,1696.14,2.38,168.42,12.42
1,2010-01-05,1140.20,1151.00,2.88,81.47,6.83,91.58,92.22,1.44,105.82,1.98,1690.62,2.34,166.87,12.43
2,2010-01-06,1129.20,1140.20,2.88,83.25,6.83,92.38,92.09,1.44,106.11,1.96,1705.32,2.37,165.38,12.23
3,2010-01-07,1138.20,1129.20,2.88,82.69,6.83,93.45,92.37,1.43,105.84,1.99,1683.45,2.41,166.69,12.20
4,2010-01-08,1128.25,1135.50,2.88,82.91,6.83,92.68,92.15,1.44,106.18,2.00,1695.26,2.42,165.25,12.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3313,2023-09-11,1325.49,1336.34,3.72,87.42,7.29,146.58,121.82,1.07,124.19,3.60,2556.88,2.35,181.81,9.04
3314,2023-09-12,1326.15,1326.05,3.73,88.94,7.29,147.08,121.77,1.08,124.21,3.60,2536.58,2.34,181.85,9.02
3315,2023-09-13,1326.59,1326.72,3.75,88.80,7.27,147.45,121.55,1.07,124.25,3.59,2534.70,2.35,182.43,9.00
3316,2023-09-14,1329.52,1328.20,3.76,90.67,7.28,147.47,121.72,1.06,124.19,3.59,2572.89,2.34,182.65,9.01
3317,2023-09-15,1328.46,1330.02,3.78,91.15,7.27,147.82,121.68,1.07,123.94,3.58,2601.28,2.35,182.61,8.98

- raw_data2

In [6]:
raw_data2 = pd.read_csv('./raw_data2.csv',encoding='euc-kr')

In [7]:
raw_data2

,날짜,달러원종가,달러원시가,CD91,WTI가,달러위안화,달러엔,달러인덱스,유로달러,유로인덱스,콜금리,코스피종가
0,2010-01-04,1150.00,1164.07,2.88,81.64,6.83,92.47,92.36,1.44,106.23,1.98,1696.14
1,2010-01-05,1140.20,1151.00,2.88,81.47,6.83,91.58,92.22,1.44,105.82,1.98,1690.62
2,2010-01-06,1129.20,1140.20,2.88,83.25,6.83,92.38,92.09,1.44,106.11,1.96,1705.32
3,2010-01-07,1138.20,1129.20,2.88,82.69,6.83,93.45,92.37,1.43,105.84,1.99,1683.45
4,2010-01-08,1128.25,1135.50,2.88,82.91,6.83,92.68,92.15,1.44,106.18,2.00,1695.26
...,...,...,...,...,...,...,...,...,...,...,...,...
3313,2023-09-11,1325.49,1336.34,3.72,87.42,7.29,146.58,121.82,1.07,124.19,3.60,2556.88
3314,2023-09-12,1326.15,1326.05,3.73,88.94,7.29,147.08,121.77,1.08,124.21,3.60,2536.58
3315,2023-09-13,1326.59,1326.72,3.75,88.80,7.27,147.45,121.55,1.07,124.25,3.59,2534.70
3316,2023-09-14,1329.52,1328.20,3.76,90.67,7.28,147.47,121.72,1.06,124.19,3.59,2572.89
3317,2023-09-15,1328.46,1330.02,3.78,91.15,7.27,147.82,121.68,1.07,123.94,3.58,2601.28

Woo_data_3

In [12]:
Woo_data_3 = pd.read_csv('./Woo_data_3.csv',encoding='euc-kr')

In [13]:
Woo_data_3

,날짜,위안화원_시,유로달러_시,코스피시가,유로인덱스_시,달러엔_시,달러위안화_시,달러원종가,달러원시가,CD91,WTI,달러인덱스,콜금리,BIR,엔원_시
0,2010-01-04,170.51,1.4325,1681.709961,92.75,92.75,6.8297,1150.00,1164.07,2.88,81.64,92.36,1.98,2.38,12.4994
1,2010-01-05,168.56,1.4409,1701.619995,92.47,92.47,6.8283,1140.20,1151.00,2.88,81.47,92.22,1.98,2.34,12.4257
2,2010-01-06,167.02,1.4364,1697.880005,91.56,91.56,6.8277,1129.20,1140.20,2.88,83.25,92.09,1.96,2.37,12.4218
3,2010-01-07,165.36,1.4407,1702.920044,92.36,92.36,6.8269,1138.20,1129.20,2.88,82.69,92.37,1.99,2.41,12.2192
4,2010-01-08,166.29,1.4320,1694.060059,93.46,93.46,6.8278,1128.25,1135.50,2.88,82.91,92.15,2.00,2.42,12.1886
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3313,2023-09-11,181.96,1.0716,2549.879883,147.02,147.02,7.3236,1325.49,1336.34,3.72,87.42,121.82,3.60,2.35,9.0903
3314,2023-09-12,181.92,1.0751,2566.419922,146.59,146.59,7.2872,1326.15,1326.05,3.73,88.94,121.77,3.60,2.34,9.0482
3315,2023-09-13,181.95,1.0754,2536.219971,147.07,147.07,7.2842,1326.59,1326.72,3.75,88.80,121.55,3.59,2.35,9.0222
3316,2023-09-14,182.67,1.0729,2544.889893,147.46,147.46,7.2732,1329.52,1328.20,3.76,90.67,121.72,3.59,2.34,9.0055
3317,2023-09-15,182.74,1.0639,2574.979980,147.49,147.49,7.2804,1328.46,1330.02,3.78,91.15,121.68,3.58,2.35,9.0180

환율신호등raw_data_

In [18]:
환율신호등raw_data_ = pd.read_csv('./환율신호등raw_data_.csv',encoding='euc-kr', index_col=0)

In [19]:
환율신호등raw_data_

,날짜,달러원종가,달러원시가,CD91,WTI가,달러위안화,달러엔,달러인덱스,유로달러,유로인덱스,콜금리,코스피종가,BIR,위안화원,엔원
0,2010-01-04,1150.00,1164.07,2.88,81.64,6.8285,92.47,92.3566,1.4413,106.23,1.980,1696.140015,2.38,168.42,12.4230
1,2010-01-05,1140.20,1151.00,2.88,81.47,6.8268,91.58,92.2236,1.4369,105.82,1.980,1690.619995,2.34,166.87,12.4313
2,2010-01-06,1129.20,1140.20,2.88,83.25,6.8278,92.38,92.0941,1.4413,106.11,1.960,1705.319946,2.37,165.38,12.2274
3,2010-01-07,1138.20,1129.20,2.88,82.69,6.8281,93.45,92.3684,1.4318,105.84,1.990,1683.449951,2.41,166.69,12.1974
4,2010-01-08,1128.25,1135.50,2.88,82.91,6.8276,92.68,92.1485,1.4413,106.18,2.000,1695.260010,2.42,165.25,12.1710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3313,2023-09-11,1325.49,1336.34,3.72,87.42,7.2882,146.58,121.8185,1.0748,124.19,3.602,2556.879883,2.35,181.81,9.0415
3314,2023-09-12,1326.15,1326.05,3.73,88.94,7.2910,147.08,121.7721,1.0752,124.21,3.597,2536.580078,2.34,181.85,9.0159
3315,2023-09-13,1326.59,1326.72,3.75,88.80,7.2700,147.45,121.5454,1.0728,124.25,3.592,2534.699951,2.35,182.43,8.9957
3316,2023-09-14,1329.52,1328.20,3.76,90.67,7.2770,147.47,121.7192,1.0641,124.19,3.587,2572.889893,2.34,182.65,9.0149
3317,2023-09-15,1328.46,1330.02,3.78,91.15,7.2744,147.82,121.6815,1.0655,123.94,3.580,2601.280029,2.35,182.61,8.9846

In [20]:
print(fin_raw_data.columns)
print(raw_data2.columns)
print(Woo_data_3.columns)
print(환율신호등raw_data_.columns)

Index(['날짜', '달러원종가', '달러원시가', 'CD91', 'WTI가', '달러위안화', '달러엔', '달러인덱스', '유로달러',
       '유로인덱스', '콜금리', '코스피종가', 'BIR', '위안화원', '엔원'],
      dtype='object')
Index(['날짜', '달러원종가', '달러원시가', 'CD91', 'WTI가', '달러위안화', '달러엔', '달러인덱스', '유로달러',
       '유로인덱스', '콜금리', '코스피종가'],
      dtype='object')
Index(['날짜', '위안화원_시', '유로달러_시', '코스피시가', '유로인덱스_시', '달러엔_시', '달러위안화_시',
       '달러원종가', '달러원시가', 'CD91', 'WTI', '달러인덱스', '콜금리', 'BIR', '엔원_시'],
      dtype='object')
Index(['날짜', '달러원종가', '달러원시가', 'CD91', 'WTI가', '달러위안화', '달러엔', '달러인덱스', '유로달러',
       '유로인덱스', '콜금리', '코스피종가', 'BIR', '위안화원', '엔원'],
      dtype='object')